name: covaccination
description: Flutter application get getting covid vaccine details

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^6.0.0
  http: ^0.12.0
  animated_text_kit: ^4.2.1
  auto_size_text: ^2.1.0
  geocoder: ^0.2.1
  intl: ^0.17.0
  url_launcher: ^6.0.3
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic